'''The Goal: Inspired by Summer Son’s Mad Libs project with Javascript.
The program will first prompt the user for a series of inputs a la Mad Libs.
For example, a singular noun, an adjective, etc. Then, once all the
information has been inputted, the program will take that data and
place them into a premade story template. You’ll need prompts for user
input, and to then print out the full story at the end with the input
included.'''

def prompts():
    print("We're going to play a game of Mad Libs.")
    print("I'm going to ask you for a series of nouns, adjectives, etc.")
    print("Based on your responses, we're going to create a goofy story.")
    print("Are you ready? Let's start with the first question")
    print("Give me an adjective")
    adjective1 = input("> ")
    print("Now give me a noun (singular)")
    noun1 = input("> ")
    print("Now give me a plural noun")
    pluralnoun1 = input("> ")
    print("Now tell me the name of a girl in the room")
    personinroom = input("> ")
    print("How about another adjective?")
    adjective2 = input("> ")
    print("I need an article of clothing.")
    articleofclothing = input("> ")
    print("Give me another noun (singular)")
    noun2 = input("> ")
    print("I need the name of a city next.")
    city = input("> ")
    print("Now another plural noun.")
    pluralnoun2 = input("> ")
    print("Next I'll need another adjective.")
    adjective3 = input("> ")
    print("Name a part of the body.")
    partofbody1 = input("> ")
    print("How about a letter of the alphabet?")
    letterofalphabet = input("> ")
    print("Name a celebrity you like (or hate).")
    celebrity = input("> ")
    print("Ok, just a few more questions... give me another plural noun.")
    pluralnoun3 = input("> ")
    print("Now I need another adjective.")
    adjective4 = input("> ")
    print("Now give me the name of a (generic) place. (i.e. a grocery store)")
    place = input("> ")
    print("Name another part of the body.")
    partofbody2 = input("> ")
    print("Another adjective, please!")
    adjective5 = input("> ")
    print("Ok, we're almost done... but I need another adjective.")
    adjective6 = input("> ")
    print("Please give me a verb.")
    verb = input("> ")
    print("Next I'll need a plural noun.")
    pluralnoun4 = input("> ")
    print("Last one! Please give me a number.")
    number = input("> ")
    # Now the story begins!!!!
    print("Alright, thanks for answering those questions!  Now enjoy your story!\n\n")
    print(f"There are many {adjective1} ways to choose a/an {noun1} to read.")
    print(f"First, you could ask for recommendations from your friends and {pluralnoun1}. ")
    print(f"Just don't ask Aunt {personinroom} - she only reads {adjective2} books ")
    print(f"with {articleofclothing}-ripping goddesses on the cover.")
    print(f"If your friends and family are no help, try checking out the {noun2} Review")
    print(f"in The {city} Times. If the {pluralnoun2} featured there are too {adjective3}")
    print(f"for your taste, try something a little more low-{partofbody1}, like {letterofalphabet}: ")
    print(f"The {celebrity} Magazine, or {pluralnoun3} Magazine. You could also choose ")
    print(f"a book the {adjective4}-fashioned way. Head to your local library or {place} ")
    print(f"and browse the shelves until something catches your {partofbody2}. ")
    print(f"Or, you could save yourself a whole lot of {adjective5} trouble and log on ")
    print(f"to www.bookish.com, the {adjective6} new website to {verb} for books!")
    print(f"With all the time you'll save not having to search for {pluralnoun4}, ")
    print(f"you can read {number} more books!")

prompts()
